name: 批量同步镜像 DockerHub/GHCR -> 同步wiki相关镜像
run-name: 镜像批量同步任务
on:
  workflow_dispatch:

env:
  SWR_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  SWR_NAMESPACE: seasky-images
  IMAGE_LIST: |
    postgres:17
    ghcr.io/requarks/wiki:2
    ghcr.io/requarks/wiki-update-companion:latest

jobs:
  sync-task:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 skopeo
        run: |
          sudo apt update -y
          sudo apt install -y skopeo

      - name: 执行批量镜像同步
        env:
          SWR_USER: ${{ secrets.SWR_USER }}
          SWR_PWD: ${{ secrets.SWR_PWD }}
        run: |
          echo "===== 目标仓库：${SWR_REGISTRY}/${SWR_NAMESPACE} ====="
          echo "${IMAGE_LIST}" | while read IMAGE_RAW; do
            [[ -z "${IMAGE_RAW}" ]] && continue

            if [[ "${IMAGE_RAW}" == ghcr.io/* ]]; then
              SRC="docker://${IMAGE_RAW}"
              IMAGE_PATH_FULL="${IMAGE_RAW#ghcr.io/}"
              # 关键修复：只保留最后一段 仓库名:tag，移除requarks/
              IMAGE_PATH="${IMAGE_PATH_FULL##*/}"
            else
              SRC="docker://docker.io/${IMAGE_RAW}"
              IMAGE_PATH="${IMAGE_RAW}"
            fi

            DST="docker://${SWR_REGISTRY}/${SWR_NAMESPACE}/${IMAGE_PATH}"

            echo "============================================="
            echo "源镜像：${SRC}"
            echo "目标镜像：${DST}"
            echo "============================================="

            for attempt in {1..3}; do
              if skopeo copy \
                --all \
                --preserve-digests \
                --retry-times 2 \
                "${SRC}" \
                "${DST}" \
                --dest-creds "${SWR_USER}:${SWR_PWD}"
              then
                echo "✅ ${IMAGE_RAW} 同步完成"
                break
              else
                echo "❌ ${IMAGE_RAW} 第${attempt}次同步失败，等待10秒重试"
                sleep 10
              fi
            done
          done
